### ISSUE TITLE
Add support for command: bitfield

### ISSUE THREAD

**Issue by filipecosta90** [redis/redis-benchmarks-specification#150]
Add support for command: bitfield. Group: bitmap Ref: https://redis.io/commands/bitfield

**Comment by slice4e** [comment]
Hey sorry - did not see that you assigned yourself here. I worked on this and submitted a pull request. Hope its OK>

**Comment by filipecosta90** [comment]
> Hey sorry - did not see that you assigned yourself here. I worked on this and submitted a pull request. Hope its OK>

NP at all. is better to have 2 PRs than none :)

**Comment by filipecosta90** [comment]
Fixed by #178
